version: "1"
services:
  postgres-user:
    container_name: postgres-user
    image: postgres
    environment:
        POSTGRES_DB: user-service
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        PGDATA: /data/postgres
    volumes:
      - ./postgres-user:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: unless-stopped

  registry-service:
    image: josip97/registry-service:latest


