module.exports = {
    BASE_URL: "http://localhost:9191/",
    TOKEN_PREFIX: "Bearer ",
    INTEREST_TAGS: [
        {value: 'VeganCuisine', label: 'Vegan Cuisine'},
        {value: 'Nightlife', label: 'Nightlife'},
        {value: 'PubCrawls', label: 'Pub Crawls'},
        {value: 'Concerts', label: 'Concerts'},
        {value: 'Brunch', label: 'Brunch'},
        {value: 'Mocktails', label: 'Mocktails'},
        {value: 'Cocktails', label: 'Cocktails'},
        {value: 'Vegetarianism', label: 'Vegetarianism'},
        {value: 'CraftBeer', label: 'Craft Beer'},
        {value: 'WineTasting', label: 'Wine Tasting'},
        {value: 'Gastronomy', label: 'Gastronomy'},
        {value: 'Exercise', label: 'Exercise'},
        {value: 'Soccer', label: 'Soccer'},
        {value: 'Basketball', label: 'Basketball'},
        {value: 'HealthyEating', label: 'Healthy Eating'},
        {value: 'Hiking', label: 'Hiking'},
        {value: 'Yoga', label: 'Yoga'},
        {value: 'Meditation', label: 'Meditation'},
        {value: 'Photography', label: 'Photography'},
        {value: 'Travel', label: 'Travel'},
        {value: 'Reading', label: 'Reading'},
        {value: 'Cooking', label: 'Cooking'},
        {value: 'Gaming', label: 'Gaming'},
        {value: 'Painting', label: 'Painting'},
        {value: 'Music', label: 'Music'},
        {value: 'Dancing', label: 'Dancing'},
        {value: 'Fashion', label: 'Fashion'},
        {value: 'Writing', label: 'Writing'},
        {value: 'Gardening', label: 'Gardening'},
        {value: 'Film', label: 'Film'},
        {value: 'Theater', label: 'Theater'},
        {value: 'Architecture', label: 'Architecture'},
        {value: 'History', label: 'History'},
        {value: 'Science', label: 'Science'},
        {value: 'Technology', label: 'Technology'},
        {value: 'Wildlife', label: 'Wildlife'},
        {value: 'Conservation', label: 'Conservation'},
        {value: 'Sustainability', label: 'Sustainability'},
        {value: 'Entrepreneurship', label: 'Entrepreneurship'},
        {value: 'Volunteering', label: 'Volunteering'},
        {value: 'Surfing', label: 'Surfing'}
    ],
    TAGS : [
        { value: 'VEGAN_CUISINE', label: 'Vegan Cuisine' },
        { value: 'NIGHTLIFE', label: 'Nightlife' },
        { value: 'PUB_CRAWLS', label: 'Pub Crawls' },
        { value: 'CONCERTS', label: 'Concerts' },
        { value: 'BRUNCH', label: 'Brunch' },
        { value: 'MOCKTAILS', label: 'Mocktails' },
        { value: 'COCKTAILS', label: 'Cocktails' },
        { value: 'VEGETARIANISM', label: 'Vegetarianism' },
        { value: 'CRAFT_BEER', label: 'Craft Beer' },
        { value: 'WINE_TASTING', label: 'Wine Tasting' },
        { value: 'GASTRONOMY', label: 'Gastronomy' },
        { value: 'EXERCISE', label: 'Exercise' },
        { value: 'SOCCER', label: 'Soccer' },
        { value: 'BASKETBALL', label: 'Basketball' },
        { value: 'HEALTHY_EATING', label: 'Healthy Eating' },
        { value: 'HIKING', label: 'Hiking' },
        { value: 'YOGA', label: 'Yoga' },
        { value: 'MEDITATION', label: 'Meditation' },
        { value: 'PHOTOGRAPHY', label: 'Photography' },
        { value: 'TRAVEL', label: 'Travel' },
        { value: 'READING', label: 'Reading' },
        { value: 'COOKING', label: 'Cooking' },
        { value: 'GAMING', label: 'Gaming' },
        { value: 'PAINTING', label: 'Painting' },
        { value: 'MUSIC', label: 'Music' },
        { value: 'DANCING', label: 'Dancing' },
        { value: 'FASHION', label: 'Fashion' },
        { value: 'WRITING', label: 'Writing' },
        { value: 'GARDENING', label: 'Gardening' },
        { value: 'FILM', label: 'Film' },
        { value: 'THEATER', label: 'Theater' },
        { value: 'ARCHITECTURE', label: 'Architecture' },
        { value: 'HISTORY', label: 'History' },
        { value: 'SCIENCE', label: 'Science' },
        { value: 'TECHNOLOGY', label: 'Technology' },
        { value: 'WILDLIFE', label: 'Wildlife' },
        { value: 'CONSERVATION', label: 'Conservation' },
        { value: 'SUSTAINABILITY', label: 'Sustainability' },
        { value: 'ENTREPRENEURSHIP', label: 'Entrepreneurship' },
        { value: 'VOLUNTEERING', label: 'Volunteering' },
        { value: 'SURFING', label: 'Surfing' }
    ]
}