spring:
  application:
    name: "API-GATEWAY"
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: 'user-service-auth'
          uri:
            'lb://USER-SERVICE'
          predicates:
            - 'Path=/user-service/api/auth/**'
          filters:
            - 'RemoveRequestHeader=Cookie'
            - 'RewritePath=/user-service/(?<segment>.*), /$\{segment}'

        - id: 'user-service-general'
          uri:
            'lb://USER-SERVICE'
          predicates:
            - 'Path=/user-service/api/user/**'
            - 'Header=Authorization, Bearer (.*)'
          filters:
            - 'RemoveRequestHeader=Cookie'
            - 'RewritePath=/user-service/(?<segment>.*), /$\{segment}'
            - 'UserServiceAuthorizationHeaderFilter'


eureka:
  client:
    serviceUrl:
      defaultZone: "http://registry-service:8761/eureka/"
      # muss eventuel angepasst werdden mit http://eureka:password@registry-service:8761

server:
  port: 9191


management:
  endpoints:
    web:
      exposure:
        include: "*"

# Routes for Employee Service
logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            handler:
              org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
