spring:
  application:
    name: "API-GATEWAY"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

## We could define the routes also like this, but the locator does this automatically and we don't need to deal with it
#      routes:
#        - id: "POST-SERVICE"
#          uri:
#            "lb://POST-SERVICE"
#          predicates:
#            - "Path=/post/**"
#
#        - id: "USER-SERVICE"
#          uri:
#            "lb://USER-SERVICE"
#          predicates:
#            - "Path=/user/**"

# Access of Dashboard here: http://localhost:8761
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

server:
  port: 9191


management:
  endpoints:
    web:
      exposure:
        include: "*"

# Routes for Employee Service
logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            handler:
              org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
