server:
  # Port 0 is used for random port number selection, allows running multiple services without handling available ports
  port: 0
  error:
    include-stacktrace: always
    include-message: always

spring:
  application:
    name: "POST-SERVICE"
  datasource:
    url: "jdbc:postgresql://localhost:5435/postService"
    username: "postgres"
    password: "bEBaGQk+RLTEBydI"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

  aop:
    proxy-target-class: true

  http:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "Spring Boot JoyJoin"
    description: "This is the JoyJoin PostService"
    version: "0.0.1"

logging:
  level:
    org:
      springframework:
        web: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: "http://CftYQ29IIX76lbg5:q0XdGl8iEygR311T@localhost:8761/eureka/"

s3:
  ENDPOINT: "https://s3.localhost.localstack.cloud:4566"
  ACCESS_KEY: "test"
  SECRET_KEY: "test"
  REGION: "us-east-1"
  BUCKET_NAME: "post-img"

api:
  API_VERSION: "api"
  BASE_URL: "http://localhost:9191/"
  BASE_URL_USER_SERVICE: ${api.BASE_URL}user-service/${api.API_VERSION}
  BASE_URL_EVENT_SERVICE: ${api.BASE_URL}event-service/${api.API_VERSION}
  BASE_URL_POST_SERVICE: ${api.BASE_URL}post-service/${api.API_VERSION}

