server:
  port: 0
  error:
    include-stacktrace: always
    include-message: always

spring:
  application:
    name: "POST-SERVICE"
  datasource:
    url: "jdbc:postgresql://postgres-post:5435/postService"
    username: "postgres"
    password: "bEBaGQk+RLTEBydI"

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

  aop:
    proxy-target-class: true

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "Spring Boot JoyJoin"
    description: "This is the JoyJoin PostService"
    version: "0.0.1"

logging:
  level:
    org:
      springframework:
        web: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: "http://CftYQ29IIX76lbg5:q0XdGl8iEygR311T@registry-service:8761/eureka/"
