server:
  # Port 0 is used for random port number selection, allows running multiple services without handling available ports
  port: 0
  error:
    include-stacktrace: always
    include-message: always

spring:
  application:
    name: "USER-SERVICE"
  datasource:
    url: "jdbc:postgresql://localhost:5436/userService"
    username: "postgres"
    password: "aHauYoTm56oG7X6u"

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

  aop:
    proxy-target-class: true

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "Spring Boot JoyJoin"
    description: "This is the JoyJoin UserService"
    version: "0.0.1"

logging:
  level:
    org:
      springframework:
        web: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: "http://CftYQ29IIX76lbg5:q0XdGl8iEygR311T@localhost:8761/eureka/"
