server:
  # Port 0 is used for random port number selection, allows running multiple services without handling available ports
  port: 0
  error:
    include-stacktrace: always
    include-message: always

spring:
  application:
    name: "EVENT-SERVICE"
  datasource:
    url: "jdbc:postgresql://localhost:5434/eventService"
    username: "postgres"
    password: "N9LoFoo3GbkEf9vV"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

  aop:
    proxy-target-class: true

  http:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"


management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "Spring Boot JoyJoin"
    description: "This is the JoyJoin UserService"
    version: "0.0.1"

logging:
  level:
    org:
      springframework:
        web: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: "http://CftYQ29IIX76lbg5:q0XdGl8iEygR311T@localhost:8761/eureka/"

s3:
  ENDPOINT: "https://s3.localhost.localstack.cloud:4566"
  ACCESS_KEY: "test"
  SECRET_KEY: "test"
  REGION: "us-east-1"
  BUCKET_NAME: "event-img"
