name: Docker Build and Push

on:
  push:
    branches:
      - main
      - development

jobs:
  user-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: josip97
          password: ${{ secrets.DOCKER_PASSWORD }}
          args: --project-dir,user-service

      - name: User-Service  Build and push Docker image
        env:
          IMAGE_NAME: josip97/user-service
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
