name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file user-service/Dockerfile --tag user-service:$(date +%s)
