name: Docker Build and Push

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    strategy:
      matrix:
        image_name: ["user-service", "post-service", "api-gateway", "event-service", "registry-service"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"

      - name: Docker login
        env:
          DOCKER_USERNAME: josip97
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push ${{matrix.image_name}}
        uses: docker/build-push-action@v4
        with:
          context: ${{matrix.image_name}}
          file: ${{matrix.image_name}}/Dockerfile
          push: true
          secrets: |
            GITHUB_TOKEN=${{ secrets.DOCKER_ACCESS_TOKEN }}