name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          server-id: docker.io
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Building and Pushing User-Service
        run: mvn package dockerfile:push --file user-service/pom.xml
        env:
          MAVEN_USERNAME: josip97
          MAVEN_PASSWORD: {{secrets.DOCKER_ACCESS_TOKEN}}