name: Docker Build and Push

on:
  push:
    branches:
      - main
      - development

env:
  REGISTRY: ghcr.io

jobs:
  build:
    strategy:
      matrix:
        image_name: ["user-service"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USERNAME: josip97
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build mvn Package
        run: mvn install
        working-directory: ${{matrix.image_name}}
      - name: Build the Docker image
        run: docker build -t josip97/${{matrix.image_name}}:${GITHUB_SHA::8} .
        working-directory: /${{matrix.image_name}}
      - name: docker push
        run: docker push josip97/${{matrix.image_name}}:${GITHUB_SHA::8}