name: Qodana
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  qodana-user-service-code-inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana User-Service'
        uses: JetBrains/qodana-action@v2023.3
        with:
          args: --project-dir,user-service
          artifact-name: qodana-user-service
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_USER_SERVICE }}

  qodana-event-service-code-inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Event-Service'
        uses: JetBrains/qodana-action@v2023.3
        with:
          args: --project-dir,event-service
          artifact-name: qodana-event-service
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_EVENT_SERVICE }}

  qodana-post-service-code-inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Post-Service'
        uses: JetBrains/qodana-action@v2023.3
        with:
          args: --project-dir,post-service
          artifact-name: qodana-post-service
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_POST_SERVICE }}